### ISSUE TITLE
А где найти - Отройте расширения для расчета цены, в появившемся способе СДЕК установите ?

### ISSUE THREAD

**Issue by cowanmax** [vityakut/joomshopping_addon_sm_cdek#1]
Установил модуль, но непонятно где искать теперь - Отройте расширения для расчета цены, в появившемся способе СДЕК ??
Спасибо!

**Comment by vityakut** [comment]
Вряд ли еще актуально, но вот)
![Снимок экрана_2021-01-28_10-18-34](https://user-images.githubusercontent.com/6539454/106103991-d5604200-6152-11eb-9dff-f6d6a3023b11.png)
